FASTER_RCNN_DETECTRON2:
  WEIGHTS: "https://huggingface.co/nlpconnect/PubLayNet-faster_rcnn_R_50_FPN_3x/resolve/main/model_final.pth"
  LABEL_MAP:
    0: "Text"
    1: "Title"
    2: "List"
    3: "Table"
    4: "Figure"

